library(phyloseq)
library(microbiomeMarker)
library(knitr)
library(dplyr)
library(ggplot2)


#SETUP
setwd("C:/Users/ccoll/Desktop/Thesis/thesis_master/comparison_and_taxonomy")
ps <- readRDS('ps_latest.RDS')

#INPUT
#in this case an input table with the most interesting taxa can be used to subset the taxa
#identified by LEfSe

genus_int <- read.table('genus_int.tsv')
#phylum_int <- read.table('phylum_int.tsv')

#rename variables
sample_data(ps)$Inside.outside <- gsub('Inside', 'Indoors', sample_data(ps)$Inside.outside)
sample_data(ps)$Inside.outside <- gsub('Outside', 'Outdoors', sample_data(ps)$Inside.outside)

#define group order for plotting
in_out_order <- c("Indoors", "Outdoors", "Both")
age_order <- c("Lactation", "Nursery", "Growing", "Finishing", "Mature")
bed_order <- c("None", "Sawdust", "Straw", "Wood chips and straw")

#The file generated by phyloseq package "ps" will be used to identify differential abundance taxa across the two data groups
lef_out<-run_lefse(ps, group = "Age_category", norm = "CPM",
                   taxa_rank = "Genus", multigrp_strat = F,
                   kw_cutoff = 0.05, lda_cutoff = 2)

#extract marker table
dat<-marker_table(lef_out) %>% data.frame() %>% select(1:5)

#adjust p-value
dat = dat %>% mutate(p.experiment =p.adjust(pvalue, method="BH"))

#visualise results
dat %>% kable(align = "c")

#uncomment to save results
#write.csv(dat, "lefse_rsults.csv")

#subset for genus/phylum > 1%
lef_out@marker_table <- lef_out@marker_table[which(lef_out@marker_table$feature %in% genus_int$genus),]
#lef_out@marker_table <- lef_out@marker_table[which(lef_out@marker_table$feature %in% phylum_int$phylum),]

#sort variables for plotting, replace 'age_order' with 'in_out_order' or any other defined order of groups
lef_out@marker_table$enrich_group <- as.character(lef_out@marker_table$enrich_group)
lef_out@marker_table$enrich_group <- factor(lef_out@marker_table$enrich_group, levels=rev(age_order))

#plot lefse
plot <- plot_ef_bar(lef_out) +
  theme(text = element_text(size = 15, face = NULL), legend.text = element_text(size=15))

#sort groups in the plot to match the order defined above, 
#replace 'age_order' with 'in_out_order' or any other defined order of groups
plot$data$enrich_group <- as.character(plot$data$enrich_group)
plot$data$enrich_group <- factor(plot$data$enrich_group, levels=age_order)
plot

#save plot
ggsave(plot, file = "lefse_age_cat.png", dpi=300, height = 200, width=370, units = "mm")


























